import Head from "next/head";
const index = () => {
  return (
    <div>
      <Head>
        <title>Dennis Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto">hi</div>
    </div>
  );
};

export default index;
