import Head from "next/head";
import Avatar from "../components/Avatar";
import Card from "../components/Card";
import LeftHeader from "../components/LeftHeader";
import IntroHeader from "../components/IntroHeader";
import Sidenav from "../components/Sidenav";
import HomeOverview from "../components/HomeOverview";
import HomeAbout from "../components/HomeAbout";
import { BriefcaseIcon } from "@heroicons/react/solid";
import Emoji from "../components/Emoji";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dennis Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="sticky top-0 z-10 bg-white shadow p-3  text-sm text-gray-700">
        <div className="flex w-full container mx-auto justify-between">
          {/* Left */}
          <div className="flex space-x-4 items-center">
            <p className="linkNav">About</p>
            <p className="linkNav">Store</p>
          </div>
          {/* Center  */}
          <div className="flex  items-center">
            <Avatar url="https://firebasestorage.googleapis.com/v0/b/dennis-portfolio-942f1.appspot.com/o/dennis.JPG?alt=media&token=bb846abf-f773-459e-ad0a-4e9b531406ef" />
            {/* <Sidenav /> */}
          </div>
          {/* Right */}
          <div className="flex space-x-4 items-center">
            <p className="linkNav">Gmail</p>
            <p className="linkNav ">Images</p>

            {/* Icon */}
            {/* <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" /> */}
          </div>
        </div>
      </header>

      {/* Main */}
      <div className="container mx-auto">
        <IntroHeader />
      </div>

      <div className="container mx-auto">
        <HomeOverview />
      </div>

      <div className="container mx-auto my-5 text-center ">
          <button className="btn">
            View Portfolio 
            {/* <BriefcaseIcon className="h-5 w-5 ml-2" /> */}
            <Emoji symbol="📁" label="folder" />
          </button>
      </div>

      {/* <HomeAbout /> */}

      <div class="container mx-auto"></div>
      {/* <LeftHeader /> */}

      {/* Footer */}
    </div>
  );
}
